INSERT INTO product (id, name, price) VALUES (1, 'ice cream',1000);
INSERT INTO product (id, name, price) VALUES (2, 'caffe latte',2000);
INSERT INTO product (id, name, price) VALUES (3, 'vanilla latte',3422);
INSERT INTO product (id, name, price) VALUES (4, 'cold brew',12131);
INSERT INTO product (id, name, price) VALUES (5, 'mocha',124124);
INSERT INTO product (id, name, price) VALUES (6, 'espresso',232);
INSERT INTO product (id, name, price) VALUES (7, 'green tea',12402);
INSERT INTO product (id, name, price) VALUES (8, 'black tea',12329);
INSERT INTO product (id, name, price) VALUES (9, 'lemonade',12312);
INSERT INTO product (id, name, price) VALUES (10, 'kkul coffee',1232131);

INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (1, 3, 3);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (2, 7, 7);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (3, 1, 1);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (4, 9, 9);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (5, 5, 5);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (6, 2, 2);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (7, 8, 8);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (8, 4, 4);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (9, 6, 6);
INSERT INTO inventory (product_id, stock, initiative_stock) VALUES (10, 0, 0);
